### ISSUE TITLE
errors during "pip install carbon"

### ISSUE THREAD

**Issue by bryndin** [graphite-project/carbon#128] opened 2013-08-08 21:55 UTC
I get "'lib/twisted/plugins/__init__.py' not found" error while trying to install carbon via pip. Tried with Twisted 8.2 installed via yum, and 13.1.0 installed via pip.

actual file is in 
  /usr/lib/python2.6/site-packages/twisted/plugins/__init__.py

"pip uninstall carbon" complains about carbon not being installed

```
Downloading/unpacking carbon
  Running setup.py egg_info for package carbon
    package init file 'lib/twisted/plugins/__init__.py' not found (or not a regular file)
    warning: no files found matching '*' under directory 'distro/'
    warning: no previously-included files found matching 'conf/*.conf'
Requirement already satisfied (use --upgrade to upgrade): twisted in /usr/lib/python2.6/site-packages (from carbon)
Requirement already satisfied (use --upgrade to upgrade): txamqp in /usr/lib/python2.6/site-packages (from carbon)
Requirement already satisfied (use --upgrade to upgrade): zope.interface>=3.6.0 in /usr/lib/python2.6/site-packages (from twisted->carbon)
Requirement already satisfied (use --upgrade to upgrade): distribute in /usr/lib/python2.6/site-packages (from zope.interface>=3.6.0->twisted->carbon)
Installing collected packages: carbon
  Running setup.py install for carbon
    package init file 'lib/twisted/plugins/__init__.py' not found (or not a regular file)
    warning: no files found matching '*' under directory 'distro/'
    warning: no previously-included files found matching 'conf/*.conf'
    changing mode of /opt/graphite/bin/carbon-cache.py to 755
    changing mode of /opt/graphite/bin/carbon-relay.py to 755
    changing mode of /opt/graphite/bin/carbon-client.py to 755
    changing mode of /opt/graphite/bin/validate-storage-schemas.py to 755
    changing mode of /opt/graphite/bin/carbon-aggregator.py to 755
Successfully installed carbon
Cleaning up...
```

**Comment by obfuscurity** [comment] 2015-01-04 05:53
The inability for pip to see that carbon is installed is related to #86. It should work if you set PYTHONPATH as specified in that issue. As mentioned previously, I'm unable to reproduce your Twisted error. Closing this issue.

**Closed by obfuscurity** 2015-01-04 05:53 UTC

**Comment by Satya2401** [comment] 2017-06-01 10:41
i am trying to install Grafite on windos machine. But getting Error in prerequisite installation stuff like Carbon and all.

**Comment by Satya2401** [comment] 2017-06-01 10:42
If anybody has installed Grafite on WINDOS machine, Please help me  in that.
