### ISSUE TITLE
carbon.agents.cache.size always increasing in 0.9.13pre1

### ISSUE THREAD

**Issue by spencert** [graphite-project/carbon#371] opened 2015-01-27 15:09 UTC
I am running the 0.9.13pre1 (specifically 36749eedce6be908109d5133bc173721d9662733) and I am noticing that the carbon.agents.*.cache.size is always increasing. 

My setup is as follows. 2 physical servers, both with 32GB RAM and 10x15K SAS disks in a RAID10. For the metric load I am sending the servers disks keep up just fine.

All metrics come into server 1 which replicates metrics to itself (0.9.12 carbon) and server 2 (0.9.13pre1 carbon) over plain-text using carbon-c-relay. The carbon.conf for the [cache] section are exactly identical and I am running two caches on each physical server. As you can see I limit the MAX_UPDATES_PER_SECOND = 500 for each cache which makes sense on this hardware. However it is clear that 0.9.13pre1 cache.size always increases whereas 0.9.12 does not.

I have attached two images which are the exact same metric targets just different hosts.

![0 9 12-carbon](https://cloud.githubusercontent.com/assets/947938/5920539/9276de3c-a5fa-11e4-8ebb-43df8fbf3b18.png)
![0 9 13pre1-carbon](https://cloud.githubusercontent.com/assets/947938/5920702/c47feb5c-a5fb-11e4-90bf-3ec0a444ac90.png)

**Comment by obfuscurity** [comment] 2015-01-27 15:15
Not that I dispute your findings, but the cache.size on the 2nd graph certainly looks like a counter and not a derivative. Can you double-check your target definition there?

**Comment by spencert** [comment] 2015-01-27 15:19
Sure thing. I thought the same thing, here is the actual URL (hostname scrubbed).

**0.9.13pre1**
http://db5234.$dayjob.com/render/?width=586&height=308&_salt=1422370542.946&from=-14days&target=alias%28sumSeries%28carbon.agents.*.cache.queues%29%2C%22cache.queues%22%29&target=alias%28secondYAxis%28sumSeries%28carbon.agents.*.cache.size%29%29%2C%22cache.size%22%29&target=alias%28sumSeries%28carbon.agents.*.metricsReceived%29%2C%22Metrics%20Received%22%29&target=alias%28sumSeries%28carbon.agents.*.updateOperations%29%2C%22Update%20Operations%22%29&title=0.9.13pre1%20Carbon

**0.9.12**
http://db1317.$dayjob.com/render/?width=586&height=308&_salt=1422370542.946&from=-14days&target=alias%28sumSeries%28carbon.agents.*.cache.queues%29%2C%22cache.queues%22%29&target=alias%28secondYAxis%28sumSeries%28carbon.agents.*.cache.size%29%29%2C%22cache.size%22%29&target=alias%28sumSeries%28carbon.agents.*.metricsReceived%29%2C%22Metrics%20Received%22%29&target=alias%28sumSeries%28carbon.agents.*.updateOperations%29%2C%22Update%20Operations%22%29&title=0.9.12%20Carbon

**Comment by obfuscurity** [comment] 2015-01-27 15:32
I'm not seeing this on my test systems, but I *am* seeing something possibly even more strange.

![104 236 119](https://cloud.githubusercontent.com/assets/494338/5921121/9121b65a-a60f-11e4-8f96-5337277eafb7.png)

Confirmed in raw output that `cache.size` is being reported with negative values. Perhaps this is related to #266. /cc @jssjr @drawks

**Comment by spencert** [comment] 2015-01-27 15:36
It appears when I change the cache.size metric to be a nonNegativeDerivative it looks much better.  However, I am not sure this is accurate either...

**0.9.13pre1**
http://db5234.oak1.omniture.com/render/?width=586&height=308&_salt=1422370542.946&from=-14days&target=alias%28sumSeries%28carbon.agents.*.cache.queues%29%2C%22cache.queues%22%29&target=alias%28secondYAxis%28nonNegativeDerivative%28sumSeries%28carbon.agents.*.cache.size%29%29%29%2C%22cache.size%22%29&target=alias%28sumSeries%28carbon.agents.*.metricsReceived%29%2C%22Metrics%20Received%22%29&target=alias%28sumSeries%28carbon.agents.*.updateOperations%29%2C%22Update%20Operations%22%29&title=0.9.13pre1%20Carbon%20with%20nonNegativeDerivative%20applied%20for%20cache.size

![0 9 13pre1-carbon-nonnegativederivative](https://cloud.githubusercontent.com/assets/947938/5921160/2c105574-a5ff-11e4-8f30-95627ab516f1.png)

**Comment by piotr1212** [comment] 2015-01-28 08:19
I've just checked on my systems. cache.size seems to be a counter on 0.9.13 and an absolute value on 0.9.12

**Comment by loopping** [comment] 2015-02-19 10:42
In cache.py, in the pop function, I have added two debug lines before returning datapoints:
<pre><code>    log.msg("pop:coun:%d" % (len(self.counts))
    log.msg("pop1:data:%d" % (self.size) )
</code></pre>
You will notice a large difference, In my case the carbon-cache receive 35k metrics per minute, after only 3 minutes.
<pre><code>19/02/2015 11:36:07 :: pop:coun:38494
19/02/2015 11:36:07 :: pop:size:267276
</code></pre>
counts is calculated this way:
<pre><code>  @property
  def counts(self):
    return [(metric, len(datapoints)) for (metric, datapoints) in self.items()]
</code></pre>

**Comment by deniszh** [comment] 2015-04-19 18:19
It seems that issue also connected with #266 - at least I see no other related changes. IMO performance gain from #266 is much more significant than that issue. We can note that change in documentation and close the issue.

**Comment by jssjr** [comment] 2015-04-22 22:10
https://github.com/graphite-project/carbon/pull/266/files#diff-b95553eddf4a9a25750a9a1d17f2be0cR66 from #266 makes me think there is a bug here if the size is no longer decreasing. Either way, I'd prefer to fix this than change the expected behavior of carbon's internal instrumentation in a patch release.

**Comment by jjneely** [comment] 2015-07-02 14:48
#408 doesn't address the MetricsCache size leak completely.  Metric data points that are dropped because of duplicate timestamps are not accounted for.  #266 has a patch for this, but I don't believe it works correctly in all configurations.  This is what I suggest:

```
--- a/lib/carbon/cache.py
+++ b/lib/carbon/cache.py
@@ -69,6 +69,10 @@
       popped = super(_MetricCache, self).pop(metric)
       ordered = sorted(dict(popped).items(), key=lambda x: x[0])
       datapoints = (metric, deque(ordered))
+      # Adjust size counter if we've dropped multiple identical timestamps
+      dropped = len(popped) - len(datapoints[1])
+      if dropped > 0:
+        self.size -= dropped
     self.size -= len(datapoints[1])
     return datapoints
```

**Comment by deniszh** [comment] 2015-07-21 13:55
Hi @jjneely ,
Tried your patch, working fine, thanks!

**Comment by AlexAkulov** [comment] 2015-09-24 19:29
@deniszh this patch must be applied on this branch https://github.com/jssjr/carbon/commits/fix_metricscache_leak
Am I right?

**Comment by deniszh** [comment] 2015-09-24 20:34
Yes, it's need to be combined with https://github.com/graphite-project/carbon/pull/408

**Comment by obfuscurity** [comment] 2015-09-27 20:24
@deniszh Would you mind closing this out once that patch gets submitted and merged? Or maybe just ref your commit accordingly. :bow:

**Comment by deniszh** [comment] 2015-09-27 21:07
PR is created https://github.com/graphite-project/carbon/pull/448, closing this issue.

**Closed by deniszh** 2015-09-27 21:07 UTC
