### ISSUE TITLE
carbon-relay hashing breaks when cache servers go down before relay

### ISSUE THREAD

**Issue by drawks** [graphite-project/carbon#28] opened 2012-08-20 20:40 UTC
20/08/2012 13:35:37 :: [console] Exception in metricReceived event handler: args=('node96', (1345494797.0, -0.718415)) kwargs={}
Traceback (most recent call last):
  File "/usr/local/share/virtualenvs/graphite-sb/lib/python2.7/site-packages/Twisted-11.0.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 460, in doRead
    rval = self.protocol.dataReceived(data)
  File "/usr/local/share/virtualenvs/graphite-sb/lib/python2.7/site-packages/Twisted-11.0.0-py2.7-linux-x86_64.egg/twisted/protocols/basic.py", line 455, in dataReceived
    self.lineReceived(line)
  File "/usr/local/share/virtualenvs/graphite-sb/lib/python2.7/site-packages/carbon/protocols.py", line 71, in lineReceived
    self.metricReceived(metric, datapoint)
  File "/usr/local/share/virtualenvs/graphite-sb/lib/python2.7/site-packages/carbon/protocols.py", line 57, in metricReceived
    events.metricReceived(metric, datapoint)
--- <exception caught here> ---
  File "/usr/local/share/virtualenvs/graphite-sb/lib/python2.7/site-packages/carbon/events.py", line 20, in **call**
    handler(_args, *_kwargs)
  File "/usr/local/share/virtualenvs/graphite-sb/lib/python2.7/site-packages/carbon/client.py", line 259, in sendDatapoint
    for destination in self.router.getDestinations(metric):
  File "/usr/local/share/virtualenvs/graphite-sb/lib/python2.7/site-packages/carbon/routers.py", line 67, in getDestinations
    for (server, instance) in self.ring.get_nodes(key):
  File "/usr/local/share/virtualenvs/graphite-sb/lib/python2.7/site-packages/carbon/hashing.py", line 46, in get_nodes  
    index = bisect.bisect_left(self.ring, search_entry) % len(self.ring)
exceptions.ZeroDivisionError: integer division or modulo by zero

Looks like once all the listed cache's have disconnected from the relay we are left calculating the modulo based on a divide by zero. If any metrics are in the receive queue, there are no caches available, and the relay goes into it's shutdown routines this exception is triggered. It may loop forever; but I'm not certain.

**Comment by piotr1212** [comment] 2019-01-11 19:46
I can't reproduce this with master. As this is 7 issue years old and no one else reported this I'm assuming it is fixed. Closing.

**Closed by piotr1212** 2019-01-11 19:46 UTC
Labels: bug
