### ISSUE TITLE
MAX_CACHE_SIZE does not limit cache dict size

### ISSUE THREAD

**Issue by cburroughs** [graphite-project/carbon#119] opened 2013-07-03 19:08 UTC
With MAX_CACHE_SIZE = 65536

carbon-cache's log file is a series of messages like:
    03/07/2013 15:03:44 :: MetricCache is full: self.size=6032686

with incrementing counts.

I'm not familiar with the code but it looks like MetricCache.store https://github.com/graphite-project/carbon/blob/master/lib/carbon/cache.py#L27 checks the size to log, but does not keep additional entires from being added.

Version:
````
Django==1.4
Python-fontconfig==0.5.1
Twisted==13.1.0
distribute==0.6.10
django-tagging==0.3.1
ethtool==0.6
iniparse==0.3.1
iotop==0.3.2
iwlib==1.0
netsnmp-python==1.0a1
pycurl==7.19.0
pygpgme==0.1
txAMQP==0.6.2
urlgrabber==3.9.1
virtualenv==1.9.1
whisper==0.9.10
yum-metadata-parser==1.1.2
zope.interface==4.0.5
````

**Comment by obfuscurity** [comment] 2016-08-31 11:29
I'm unable to reproduce this with HEAD in the master branch. I suspect this was fixed a while back so I'll close this now but if you're still experiencing this problem please let us know your carbon version and we'll dig further.

**Closed by obfuscurity** 2016-08-31 11:29 UTC
