### ISSUE TITLE
MetricPickleReceiver MAX_LENGTH limit in 65536

### ISSUE THREAD

**Issue by dreampuf** [graphite-project/carbon#215] opened 2014-02-14 10:00 UTC
```python
class MetricPickleReceiver(MetricReceiver, Int32StringReceiver):
  MAX_LENGTH = 2 ** 20
  def dataReceived(self, data):
    print len(data), "dr"
```

```bash
$ ./bin/carbon-cache.py --debug start
Starting carbon-cache (instance a)
14/02/2014 09:56:06 :: [console] Log opened.
14/02/2014 09:56:06 :: [console] twistd 13.2.0 (/opt/venv/bin/python2.6 2.6.8) starting up.
14/02/2014 09:56:06 :: [console] reactor class: twisted.internet.epollreactor.EPollReactor.
14/02/2014 09:56:06 :: [console] ServerFactory starting on 2003
14/02/2014 09:56:06 :: [console] Starting factory <twisted.internet.protocol.ServerFactory instance at 0x19f13c68>
14/02/2014 09:56:06 :: [console] ServerFactory starting on 2004
14/02/2014 09:56:06 :: [console] Starting factory <twisted.internet.protocol.ServerFactory instance at 0x19f3f2d8>
14/02/2014 09:56:06 :: [console] ServerFactory starting on 7002
14/02/2014 09:56:06 :: [console] Starting factory <twisted.internet.protocol.ServerFactory instance at 0x19f3f3f8>
14/02/2014 09:56:18 :: [listener] MetricPickleReceiver connection with 127.0.0.1:51935 established
14/02/2014 09:56:18 :: [console] 65536 dr
14/02/2014 09:56:18 :: [listener] MetricPickleReceiver connection with 127.0.0.1:51935 closed cleanly
```

But we already set the `MAX_LENGTH` is `2 ** 20`. Is that cause by system configuration ?

**Comment by obfuscurity** [comment] 2016-08-30 18:09
Sorry, I don't see an actual question or bug report in here. Can you elaborate?

**Comment by obfuscurity** [comment] 2016-08-30 18:11
https://github.com/graphite-project/carbon/commit/a7f86dadc2884d0001a1262b3ac95e384aa6833b introduced this particular limit, but I don't have any context for the change aside from the commit log message.

**Comment by obfuscurity** [comment] 2016-08-30 18:14
Oh, and note that it looks like `MAX_LENGTH` here is a noop. I don't see it used anywhere else.

**Comment by obfuscurity** [comment] 2016-08-30 18:22
Again, not sure what the original question might have been. The `MAX_LENGTH` of the pickle string is 1MB. @syepes' test seems to confirm that everything is working as intended. Closing this out but please let me know if there are any issues that still need to be addressed.

**Closed by obfuscurity** 2016-08-30 18:22 UTC

**Comment by dreampuf** [comment] 2016-08-31 06:50
@obfuscurity I guess (yes, I almost forget this issue) that is about customized `MAX_LENGTH` not work. Just FYI.
